### ISSUE TITLE
Changing Geant4 physics flags 

### ISSUE THREAD

**Issue by simonge** [AIDASoft/DD4hep#1010]
Hi All,

I am wanting to turn on the synchrotron physics process from Geant4EmExtraPhysics. Usually either achieved before initialization in the geant4 macro file using e.g.
`/physics_lists/em/SyncRadiation true`
or in the code with:
`synActivated(true)`

Is there a way to call this without writing a plugin? If I understand correctly the ability to call PreInit Geant4 macro commands before the initialization would solve our issue and introduce this functionality for any other such processes?

@wdconinc

**Comment by wdconinc** [comment]
My thoughts on this. I know we could write a plugin for this, Geant4EmExtraPhysics or so, but this seems like adding more maintenance burden to dd4hep. I wonder if there is a better way to resolve this inside dd4hep.

As @simonge pointed out, the key issue is that this physics requires flags to be set before initialization and cannot be loaded after initialization. For example, let's say we want synchrotron radiation enabled in the FTFP_BERT list, then we'd load [FTFP_BERT.cc](https://github.com/Geant4/geant4/blob/master/source/physics_lists/lists/src/FTFP_BERT.cc), which registers `RegisterPhysics( new G4EmExtraPhysics(ver) );`, but that doesn't do anything since G4EmExtraPhysics starts with [pretty much everything disabled](https://github.com/Geant4/geant4/blob/master/source/physics_lists/constructors/gamma_lepto_nuclear/src/G4EmExtraPhysics.cc#L131).

So, between [loading the physics list](https://github.com/AIDASoft/DD4hep/blob/master/DDG4/python/DDSim/DD4hepSimulation.py#L475) and [initializing the kernel](https://github.com/AIDASoft/DD4hep/blob/master/DDG4/python/DDSim/DD4hepSimulation.py#L486) we need to inject the enabling of synchrotron radiation. That appears to be something for [`setupUserPhysics`](https://github.com/AIDASoft/DD4hep/blob/master/DDG4/python/DDSim/Helper/Physics.py#L146), so maybe we can add something like this to the steering file:
```python
def setupSynchrotonRadiation(kernel):
    kernel.getUI().ApplyCommand('/physics_lists/em/SyncRadiation true')
    return None
SIM.physics.setupUserPhysics(setupSynchrotronRadiation)
```
... but that's where I got...

**Comment by MarkusFrankATcernch** [comment]
Please close if required functionality is present...

**Comment by andresailer** [comment]
I think one (me) needs to add interfaces in ddsim still

**Comment by simonge** [comment]
> 

Thanks, just checking to see if I was missing something.

**Comment by MarkusFrankATcernch** [comment]
@simonge Can we close this issue ?

**Comment by andresailer** [comment]
I still need to work this out, I think.

**Comment by andresailer** [comment]
Hi @simonge , @wdconinc 

The necessary interfaces for this were now merged, so if you could give this a go!

Thanks,
Andre

**Comment by wdconinc** [comment]
I'll try to backport this into our environment today, which will make it easier for @simonge to test.

**Comment by simonge** [comment]
Thanks both, I'll try and play with this before the end of the week.
