### ISSUE TITLE
Impossible to include plugin definitions from an external XML file

### ISSUE THREAD

**Issue by bartosik-hep** [AIDASoft/DD4hep#1062]
It is often necessary to have several versions of the same geometry with some parts of it excluded, e.g. for an event display.  
This calls for the root XML file of a geometry to be reduced to just `<include>` tags for the relevant components, to minimize code duplication.

In the present version it seems impossible to include the `<plugins>` section from an external file. The two ways tried in the example below have failed.

1. [Version 1](https://github.com/MuonColliderSoft/detector-simulation/blob/dd4hep-issue-plugins/geometries/MuColl_v1.0.1/MuColl_v1.xml) - standard `<include ref=".."/>`

2. [Version 2](https://github.com/MuonColliderSoft/detector-simulation/blob/dd4hep-issue-plugins/geometries/MuColl_v1.0.1/MuColl_v1_mod1.xml) - including via `<includes> <file ref="..."/> </includes>`

In both cases XML parsers complains with the following error:
```bash
$ checkGeometry -c MuColl_v1.xml

TypeError: none of the 2 overloaded methods succeeded. Full details:
  void dd4hep::DetectorImp::fromXML(const string& fname, dd4hep::DetectorBuildType type = BUILD_DEFAULT) =>
    runtime_error: detectorTypes: Call only available once the geometry is closed!
dd4hep: with plugin:InstallSurfaceManager
dd4hep: Error interpreting XML nodes of type <plugin/>
dd4hep: Error interpreting XML nodes of type <plugins/>
dd4hep: Error interpreting XML nodes of type <include/>
dd4hep: while parsing MuColl_v1.xml
  void dd4hep::DetectorImp::fromXML(const string& fname, dd4hep::xml::UriReader* entity_resolver, dd4hep::DetectorBuildType type = BUILD_DEFAULT) =>
    TypeError: takes at least 2 arguments (1 given)
```

 - OS version: `centos8`
 - Compiler version: `GCC 8.5.0`
 - Package version: `v01-16`
 - Goal: Include the `<plugins> ... </plugins>` section from an external file for a more concise geometry description
 - Reproduced by:
 ```bash
git clone https://github.com/MuonColliderSoft/detector-simulation.git
cd detector-simulation
git checkout dd4hep-issue-plugins
cd geometries/MuColl_v1.0.1/
checkGeometry -c MuColl_v1.xml
checkGeometry -c MuColl_v1_mod1.xml
```

**Comment by MarkusFrankATcernch** [comment]
@bartosik-hep This is unfortunately one of these corner cases, which cannot be solved in a generic way. For various reasons the plugins should be executed at the end of the geometry processing, because most plugins require the "full" geometry and not only some part there-of. Hence this behavior should be kept.

A hack for the first level (ie. the top xml input file) could be done, by allowing `include` directives inside the top level `plugins` directive, processed at the end of the parsing like for example:
```
<plugins>
  <include  ref="..."/>
</plugins>
```
but this is still a hack, because for already included files this would fail as well. For this reason I do not like this solution.
Another negative side-effect of such an approach is the intended sequence of calls: dependent when the `include` directives should be processed there may be unintended execution of plugins happening.

However, there is another way to invoke xml-parsing/processing sequentially like:
`$> geoDisplay -input <xml-file-1> -input <xml-file-2> .... -input <xml-file-n> .... `
where `<xml-file-2>` could be something like:
```
<lccdd>
   <includes>
     <include ref="include/plugins.xml"/>
   </includes>
</lccdd>
```
Would such an approach solve your problem as well?
I cannot tell you exactly if all utility apps handle multiple inputs, but this probably should then rather be fixed at this level.

**Comment by bartosik-hep** [comment]
@MarkusFrankATcernch thank you for suggestions, but neither of them works.
The 2nd approach is not really an option, because it breaks the assumption of having a single specific file defining the detector geometry, used throughout our simulation framework.

The 1st hack would be acceptable for us, but it doesn't really work. I've committed another test version to the repository implementing your hack, and it looks like the `<include ref = "..."/>` statement is ignored by the parser.

If you try the following example:

```bash
git clone https://github.com/MuonColliderSoft/detector-simulation.git
cd detector-simulation
git checkout dd4hep-issue-plugins
cd geometries/MuColl_v1.0.1/
checkGeometry -c MuColl_v1_mod2.xml
```

it doesn't show any errors, despite there are lines in [`include/plugins_mod2.xml`](https://github.com/MuonColliderSoft/detector-simulation/blob/dd4hep-issue-plugins/geometries/MuColl_v1.0.1/include/plugins_mod2.xml) referring to subdetectors commented in the root file [`MuColl_v1_mod2.xml`](https://github.com/MuonColliderSoft/detector-simulation/blob/dd4hep-issue-plugins/geometries/MuColl_v1.0.1/MuColl_v1_mod2.xml).

You can see the expected errors when running the version with all the plugins included inline:

```bash
checkGeometry -c MuColl_v1_inline.xml

. . .
Traceback (most recent call last):
  File "/opt/ilcsoft/muonc/DD4hep/v01-16/bin/checkGeometry", line 80, in <module>
    description.fromXML(opts.compact)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  void dd4hep::DetectorImp::fromXML(const string& fname, dd4hep::DetectorBuildType type = BUILD_DEFAULT) =>
    runtime_error: dd4hep: Evaluator::Object : unknown variable : InnerTracker_Barrel_half_length_0 : value=InnerTracker_Barrel_half_length_0 [Evaluation error]
```

**Comment by MarkusFrankATcernch** [comment]
@bartosik-hep Please see: https://github.com/AIDASoft/DD4hep/pull/1066

**Comment by MarkusFrankATcernch** [comment]
Please see https://github.com/AIDASoft/DD4hep/pull/1071
Should be merged soon.

**Comment by bartosik-hep** [comment]
That looks great. Thank you!
