### ISSUE TITLE
Charge sharing across tracker segmentation

### ISSUE THREAD

**Issue by simonge** [AIDASoft/DD4hep#1167]
I am interested in introducing charge sharing parameterizations to some simulated silicon detectors. Is this a proposed feature of DDDigi? Is there any ongoing work in this direction?

**Comment by MarkusFrankATcernch** [comment]
Hi Simon,

Yes. This in principle is an issue for DDDigi.
However, there is a more fundamental problem with DDDigi: I am missing customers.
Without real-world users it is very difficult to develop applications which are also usable and useful 
outside of lab-conditions. DDG4 was a very good example here, because the developments were driven by the
users from the linear collider community. Typically after some initial thrust then things run by themselves....

The LHC will have its winter shutdown in a couple of weeks and I expect to be able to dedicate again more time to dd4hep.
Hence, if you would be able to again dedicate more time to the DDDigi development. If you would be willing to sort of
help steering requirements and help to define necessary developments this would give a substantial push to DDDigi.

Hope hearing from you!

Cheers,
Markus

**Comment by MarkusFrankATcernch** [comment]
@simonge Hi Simon,
any interest to get here something started together? Otherwise we should close this issue.
Markus

**Comment by simonge** [comment]
@wdconinc I feel this is above my pay grade to decide if we pursue implementation of this, among other digitization tasks within DDDigi framework, call the relevant functions from JANA, or continue to develop a separate code base (seems a bit wasteful when lots of this is already here or future developments would be useful for other projects).

**Comment by wdconinc** [comment]
@simonge You are correct, that I am hoping that we can reuse a lot of DDDigi. At this point we're not doing that because of a bit of a mismatch of what people choose to do when they need something quickly (hack something together...), and what they know (or don't know) is available in DDDigi. I think if there is a better understanding of what DDDigi can do, and if there are some examples in our geometry and digitization for a variety of use cases, then it would be easier to get traction on using more of DDDigi, and we could focus development effort on implementing features that we need and are missing (such as charge sharing).

@MarkusFrankATcernch There has been a lot of development in DDDigi over the past year, and I wonder if there are places we should be looking at for use cases or documentation that we might not be aware of. Maybe this is something that we can also discuss with the key4hep folks at a monthly meeting.

**Comment by MarkusFrankATcernch** [comment]
@wdconinc If you use DDDigi or parts thereof, you have to tell me which parts would be missing - or if the overall architecture is useless.
As I said before, I can only program against user requirements. These however I currently do not have....

**Comment by MarkusFrankATcernch** [comment]
@wdconinc Issue closed. If you use DDDigi and want improvements, please tell I am happy to improve it.
In principle I should improve it - I have some commitment from AIDA innove, but as said: without clients
can't do it.
