### ISSUE TITLE
Using rotation in DDCAD to rotate around z axis

### ISSUE THREAD

**Issue by armin-ilg** [AIDASoft/DD4hep#1200]
- OS version: lxplus7
 - Release: Latest key4hep release (/cvmfs/sw.hsf.org/key4hep/releases/2023-11-23/x86_64-centos7-gcc12.2.0-opt/key4hep-stack/2023-11-30-yi2hqy/setup.sh)
 - Package version:master
 - Reproduced by: Generating root file of geometry of [examples/DDCAD/compact/DD4hep_Issue_1134.xml](https://github.com/AIDASoft/DD4hep/blob/e47d56922873a54f73ceb6df67a2d65e41e0c1c2/examples/DDCAD/compact/DD4hep_Issue_1134.xml#L4) using [script from k4geo](https://github.com/key4hep/k4geo/blob/main/scripts/save_detector_to_root.sh). Looking at the resulting geometry in a TBrowser yields:
![Screenshot 2023-12-13 at 11 44 29](https://github.com/AIDASoft/DD4hep/assets/11501463/ae474472-cc3b-4b6d-b735-7a666be4176e)
where the Z axis goes through the two volumes. I now want to rotate around the Z axis, but doing so by setting z="4*pi/8*rad" in 
[examples/DDCAD/compact/DD4hep_Issue_1134.xml](https://github.com/AIDASoft/DD4hep/blob/e47d56922873a54f73ceb6df67a2d65e41e0c1c2/examples/DDCAD/compact/DD4hep_Issue_1134.xml#L4) rotates around another axis:
![Screenshot 2023-12-13 at 11 38 45](https://github.com/AIDASoft/DD4hep/assets/11501463/492cf5d7-e036-4f84-9046-570be0971148)
If I instead change the angle in x or y, this also never yields in a rotation around the z axis. On a first look I didn't find the source of this problem in DD4hep. Do you have an idea where the issue could come from?

Thank you and kind regards,
Armin

**Comment by MarkusFrankATcernch** [comment]
@armin-ilg 
I am afraid this is not as simple as that.

The CAD volume of the STL file is NOT positioned at the origin of its volume frame.
(Remove the transformation in the xml to see where it originally is).
In order to simply use a Z-rotation you will probably need to place the current setup into an assembly with 
a coordinate frame in the true origin. Then you can rotate this "envelope-assembly" the way you want.
Just changing the Z rotation cannot really work. Also keep in mind you deal here with a ZYX rotation.

**Comment by MarkusFrankATcernch** [comment]
Please see PR 1259 on an example how to properly deal with CAD shapes, which are not placed at the origin.
![Screenshot from 2024-05-07 11-14-46](https://github.com/AIDASoft/DD4hep/assets/8831087/249dab7c-ac83-49ac-8427-709fc19ee0db)
