### ISSUE TITLE
FATAL when running ddsim on Whizhard stdhep output file

### ISSUE THREAD

**Issue by asciandr** [AIDASoft/DD4hep#1222]
A FATAL is thrown out when trying to run CLD full simulation on a Whizhard stdhep output: 
```
Geant4Output2EDM4hep INFO  Opened out_test2.root for output
GenerationInit   INFO  +++ Initializing event 1. Within run:0 event 1.
LCIOStdHepReader::moveToEvent INFO  Event number after skipping: 0
STDHEP4          INFO  +++ Particle interaction with 102 generator particles and 4 vertices ++++++++++++++++++++++++
PrimaryHandler   INFO  +++++ G4PrimaryVertex at (+0.00e+00,+0.00e+00,+0.00e+00) [mm] +0.00e+00 [ns]
Input            FATAL +++ Stable particle (PDG: 12        ) with daughters! check your MC record, adapt particle.tbl file...
Geant4Kernel     FATAL +++ Exception while simulating:Cannot Simmulate this MC Record
```
The error message seems to suggest that there are issues with long-lived particles having a non-standard status which is badly interpreted within ddsim.

 - OS version: Alma9 (on lxplus)
 - Package version: setting key4hep nightly (`source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh`)
 - Reproduced by: 
`ddsim --compactFile $K4GEO/FCCee/CLD/compact/CLD_o2_v05/CLD_o2_v05.xml --numberOfEvents 3 --inputFiles ~asciandr/work/public/forBrieuc/test.stdhep --outputFile out.root `
 - Goal: Run CLD full simulation on Whizhard stdhep output files (HEPMC3 should be possible and working, already?)

**Comment by andresailer** [comment]
Hi @asciandr 

These are not long-lived particles, these are stable particles when it comes to Geant4.

https://github.com/AIDASoft/DD4hep/blob/8bed96f00aa1f9d396d54dc793dbb731ed43a6aa/DDG4/examples/particle.tbl#L35-L44

ddsim correctly interprets the status and refuses to do anything with this record. Trying to pass this record to Geant4 leads to worse error messages or totally incorrect results. Apparently, we have never encountered neutrinos with pre-assigned decays before.

However, unless you can convince Whizard to not pass the neutrinos through some additional level, which causes the "decay" of the neutrino to show up in the MC Record, you can ignore neutrinos in ddsim.

Note the last three numbers: 12, 14, 16 which I added from the default
```python
SIM.physics.rejectPDGs = {1, 2, 3, 4, 5, 6, 3201, 3203, 4101, 4103, 21, 23, 24, 5401, 25, 5403, 2203, 3101, 3103, 4403, 2101, 5301, 2103, 5303, 4301, 1103, 4303, 5201, 5203, 3303, 4201, 4203, 5101, 5103, 5503, 12, 14, 16}
```

https://github.com/AIDASoft/DD4hep/blob/8bed96f00aa1f9d396d54dc793dbb731ed43a6aa/DDG4/python/DDSim/Helper/Physics.py#L21-L27


>  (HEPMC3 should be possible and working, already?)

In the HepMC3 case the error should be the same, because the MC Record is independent of the file type.

Cheers,
Andre

**Comment by asciandr** [comment]
Thanks for the prompt reply with explanations and fixes, @andresailer ! Shall I open a PR myself or are you going to do that?

Cheers,
Andrea

**Comment by andresailer** [comment]
We cannot make that the default. There are cases where neutrinos should be simulated so that the resulting MC record is consistent.

You will need to set these numbers when you do your own simulation.

Thanks for your understanding!
Andre

**Comment by andresailer** [comment]
```
ddsim --compactFile $DD4hepINSTALL/DDDetectors/compact/SiD.xml --numberOfEvents 3 --inputFiles ../../a/asciandr/work/public/forBrieuc/test.stdhep --outputFile test_out.root --physics.rejectPDGs "12 14 16"
```

**Comment by asciandr** [comment]
Thanks a lot, @andresailer !
