### ISSUE TITLE
plugins in included compact file are not executed

### ISSUE THREAD

**Issue by gaede** [AIDASoft/DD4hep#198]
global plugins like the SurfaceInstaller cannot be defined in an included xml file, like here:
https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_l4_v02/ILD_l4_v02.xml#L73
with:
https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_common_v02/plugins.xml
Is this a feature or a bug ?

**Comment by andresailer** [comment]
You need to put everything in `<lccdd>` tags, like here: https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v11/ECalBarrel_o2_v01_02.xml#L54 I think

**Comment by gaede** [comment]
Adding <lccdd> tags did not work, either ...

**Comment by petricm** [comment]
Have you solved this? Otherwise I think the `<include ref=` only works in the global scope (`<lccdd>`), but you have it in `<define>`. This is the same as in [here](https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v11/InnerTracker_o2_v06_01.xml#L151) where the include does not really "copy" the include file as in global scope, but you have to do it by hand like [here](https://github.com/iLCSoft/lcgeo/blob/master/detector/tracker/TrackerBarrel_o1_v05_geo.cpp#L93)

**Comment by petricm** [comment]
After a discussion with @MarkusFrankATcernch at the Developer Meeting your problem was most likely due to the ordering of `xml` tags. For instance if you define a `<plugin>` that should be executed on a detector the plugin should be behind `<detector>`. To be more precise the `<plugin>` tag is evaluated last of all tags. The exact order of tag evaluation is given in [this function](https://github.com/AIDASoft/DD4hep/blob/master/DDCore/src/plugins/Compact2Objects.cpp#L1087) and you can see that first form [L1119](https://github.com/AIDASoft/DD4hep/blob/master/DDCore/src/plugins/Compact2Objects.cpp#L1119) `that first <defines>` then `<include>` are evaluated and at last `<plugins>` which means that **the plugins tag must always be the last tag in a `xml` file** if you want to be safe.
