### ISSUE TITLE
GLXBadContext

### ISSUE THREAD

**Issue by jstrube** [AIDASoft/DD4hep#21]
I'm trying to visualize a detector, but I'm hitting a GLXBadContext, and then the visualization freezes. Here's how to reproduce.

```
svn co https://svnsrv.desy.de/public/ddsim/lcgeo/trunk lcgeo
rm lcgeo/detector/calorimeter/SHcal*
rm lcgeo/detector/calorimeter/SEcal*
rm lcgeo/detector/CaloTB/CaloPrototype*
mkdir lcgeo/build
source /cvmfs/sft.cern.ch/lcg/releases/gcc/4.8.4/x86_64-slc6/setup.sh
source /cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-10/init_ilcsoft.sh
cd lcgeo/build/
cmake -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` -C /cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-10/ILCSoft.cmake ..
make -j4
make install
cd ../
source bin/thislcgeo.sh
geoDisplay SiD/compact/sidloi3/sidloi3_v00.xml
```

I'm getting this error message

```
Info in <TGeoManager::SetVisLevel>: Automatic visible depth disabled
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
Error in <RootX11ErrorHandler>: GLXBadContext (XID: 6291640, XREQ: 150)
```

What am I doing wrong?

**Comment by jlingema** [comment]
Hi, I had a similar problem which turned out to be a problem with X11 rather than ROOT. A solution is mentioned at the end of [this thread](https://sft.its.cern.ch/jira/browse/ROOT-8246)

**Comment by petricm** [comment]
If this is on a mac, and you are trying to display from a remote machine there is a X11 problem as @jlingema said. We suggest downgrading to 2.7.8. (this certainly solved problems on a mac for us), but you can also check 2.7.10 if this also helps as suggested in the thread.

**Comment by jstrube** [comment]
That worked, thanks!

**Comment by asteinhebel** [comment]
I encounter this error without the use of a Mac. With the same initialization, I get this error both on my local computer (running Scientific Linux 6.8) and when ssh-ing into the lxplus from this SL6 machine. 

I imagine that it's something to do with my machine, but since it's not a Mac I haven't found any suggestions thus far.

**Comment by asteinhebel** [comment]
I've found some more details relating to this on my local machine.

glxgears runs perfectly fine, but outputs some errors
`libGL error: unable to load driver: nouveau_dri.so`
`libGL error: driver pointer missing`
`libGL error: failed to load driver: nouveau`

I've been doing most of my work through the /cvmfs so at the beginning of each session I initialize with
`source /afs/cern.ch/eng/clic/software/DIRAC/bashrc`
`source /cvmfs/sft.cern.ch/lcg/releases/gcc/4.8.4/x86_64-slc6/setup.sh`
`source /cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-10/init_ilcsoft.sh`
`source /afs/cern.ch/eng/clic/software/setup.sh`
`cd lcgeo/`
`source bin/thislcgeo.sh`

After the ..../init_ilcsoft.sh file is sourced, glxgears cannot create the animation at all and outputs
`X Error of failed request:  BadValue (integer parameter out of range for operation)`
 ` Major opcode of failed request:  155 (GLX)`
  `Minor opcode of failed request:  3 (X_GLXCreateContext)`
  `Value in failed request:  0x0`
  `Serial number of failed request:  21`
  `Current serial number in output stream:  23`

None of the other initialization commands have any affect on glxgears, but I need to continue sourcing all the initialization in order to create the detector geometry that I'm trying to visualize with geoDisplay.

**Comment by petricm** [comment]
Hi,
a.)I know this is not the problem, but if you have a SLC6.8 machine, why do you ssh -Y to lxplus and run geoDisplay there? Why don't you do it on your machine?

b.)When you initialize iLCSoft just source this (this has all the necessary stuff in it):
` source /cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-10/init_ilcsoft.sh`
and **don't** execute this
` source /afs/cern.ch/eng/clic/software/DIRAC/bashrc`
` source /cvmfs/sft.cern.ch/lcg/releases/gcc/4.8.4/x86_64-slc6/setup.sh`
` source /afs/cern.ch/eng/clic/software/setup.sh`

c.)Now try to run geoDispaly. What do you get? 

d.)After sourcing init_ilcsoft.sh set
`export LIBGL_ALWAYS_INDIRECT=0`
What do you get now?

Cheers,
Marko

**Comment by asteinhebel** [comment]
a) For the post above and in the following, I was(am) working on my own machine (not through lxplus). I had just wanted to mention that I had the same error with both computers.

I should clarify that I'm trying to visualize a different file that the one originally mentioned, /lcgeo/SiD/compact/SiD_o1_v01/SiD_o3_v01.xml .

c) Doing this freezes the computation and gives the error,
`Info in <TGeoManager::SetVisLevel>: Automatic visible depth disabled`
`Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1`
`Error in <RootX11ErrorHandler>: GLXBadContext (XID: 109052267, XREQ: 155)`

d) Here, I get the same error as in part c) but with XID=71303531

**Comment by andresailer** [comment]
Trying to reproduce the problem: 

1) You mean `SiD_o1_v03.xml`, right? Because I don't see SiD_o3_v01

2) The geoDisplay from `/cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-10/init_ilcsoft.sh` always crashes my X-server

3) Can you try when sourcing only: 
`/cvmfs/clicdp.cern.ch/iLCSoft/builds/2016-09-27/x86_64-slc6-gcc48-opt/init_ilcsoft.sh`

4) The Model SiD_o1_v03.xml shows many overlaps (geant4 shell /geometry/test/run )

**Comment by asteinhebel** [comment]
1) Yes, I do mean that. Sorry for the misinformation

2), 3) That worked!!  The GL viewer finally loads and is interactive. I see a few errors still in the output
`libGL error: unable to load driver: nouveau_dri.so`
`libGL error: driver pointer missing`
`libGL error: failed to load driver: nouveau`
I don't know how crucial these are, since the image is now working.

**Comment by andresailer** [comment]
Can we consider this problem solved?

**Comment by asteinhebel** [comment]
Yes, thanks again!

**Comment by jstrube** [comment]
Is it known why /cvmfs/ilc.desy.de/sw/x86_64_gcc48_sl6/v01-17-10/init_ilcsoft.sh crashes the X server? 
It doesn't look like anything was actually fixed here.

**Comment by protopopescu** [comment]
I agree with @jstrube: since the ILCsoft configuration is different from the one used by Amanda to run ddsim this will introduce a new set of problems ...

**Comment by petricm** [comment]
It is a TEve problem, which is described [here](https://twiki.cern.ch/twiki/bin/view/CLIC/BuildingILCSOFTatCERN) under "Use local installation of ROOT and Python". 

If you execute 
`find graf3d/eve/src/TEve*GL.cxx -type f -exec sed -i 's/\/\/\ fDLCache\ /fDLCache\ /g' {} \;` 
and rebuilt it should work
