### ISSUE TITLE
RootMap not installed in right place

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#212]
The RootMap is not installed in right lib folder

**Comment by jhrdinka** [comment]
We just install all our targets in CMAKE_INSTALL_LIBDIR, which should take the right repository.

**Comment by andresailer** [comment]
And how do you call cmake for dd4hep to install libraries in lib64?

**Comment by jhrdinka** [comment]
I think it depends on the system where the libraries get installed. I guess you need to change `lib `[here](https://github.com/AIDASoft/DD4hep/blob/57a4ef32e3c22ed39c200ae6de4606816828221d/cmake/DD4hep.cmake#L113) into ${CMAKE_INSTALL_LIBDIR}

**Comment by andresailer** [comment]
There is no use of `CMAKE_INSTALL_LIBDIR` at the moment in dd4hep, so I would like to understand where you are setting CMAKE_INSTALL_LIBDIR.

**Comment by jhrdinka** [comment]
We are not setting it anywhere explicitly. I guess it just takes the corresponding LIBDIR depending on the architecture (https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html).

**Comment by andresailer** [comment]
There is also no use of GNUInstallDirs in DD4hep. And all the other install calls use "lib" as a folder (for libraries). I still don't understand how you manage to get anything installed in lib64.
You do get your libraries already installed into the lib64 folder, right?
(What OS, platform, etc.?)

**Comment by andresailer** [comment]
Just changing that line gives
```
CMake Error at cmake/DD4hep.cmake:112 (install):
  install FILES given no DESTINATION!
```
if the variable is not set in the cmake call.

**Comment by jhrdinka** [comment]
I think if you want to use GNUInstallDirs you need to include `include (GNUInstallDirs)` in your top CMake File (as we do here: https://gitlab.cern.ch/acts/a-common-tracking-sw/blob/master/CMakeLists.txt#L18). For me (I am using slc6) it gets installed in lib64, while for other users e.g. it gets installed in lib.

**Comment by andresailer** [comment]
I am still trying to fully understand the problem here.
You are saying (said in yesterday's meeting) that the dd4hep libraries are installed in `lib64` on your operating system, but the components/rootdicts/pcms  are not? 

All destinations in DD4hep are lib; I am using slc6; I get everything installed in the lib folder.
What are you doing to get the dd4hep libraries installed into the lib64 folder?

**Comment by jhrdinka** [comment]
Just my detector library (containing the DD4hep detector constructors) which uses DD4hep is getting installed in `lib64`, not the DD4hep libraries itself. The Problem is that we are using `dd4hep_generate_rootmap` which generates the rootmap for the detectors in `lib`, while the corresponding library is installed in `lib64`. Therefore to build the detector the user needs to set the `LD_LIBARARY_PATH` to both `lib` and l`ib64`

**Comment by andresailer** [comment]
Ahhh, now I understand
