### ISSUE TITLE
Working with TGeo limitations

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#286]
Hi Everyone,

Recently came across this limitation in TGeo: I needed a tessellated solid, but TGeo does not have a tessellated "shape". I was using the [CADMesh library](https://github.com/christopherpoole/CADMesh) which is quite nice. This also implies that TGeo does not have full coverage of GDML schema where (I assume) G4 does. AFAIK G4 could be incomplete as well, however it is certainly more complete than TGeo.

Defining the current problem:
Say I absolutely must use tessellated solids in my simulation geometry, but I don't need to visualize or do anything else root with these volumes. What is the best way to include this DD4hep? Furthermore, assume the volumes are not sensitive.

Another way of phrasing the problem: How can I use a G4 solid construction which does not exist in TGeo?

Generally looking towards the future how do you (the developers) see the geometry situation playing out? Is it worth adding/improving TGeo's "shape" coverage or is something like VecGeom going to provide a less repetitive path forward?

From my naive perspective, factorizing G4's geometry into standalone library would be great. (Of course where the lines are drawn would have varying drawbacks but the idea is nice.) This way TGeo doesn't have to mirror G4. Possibly VecGeom would achieve the same thing but I don't think this VecGeom's primary goal; it is more of a nice side effect.

Happy New Year!

**Comment by petricm** [comment]
Dear @whit2333,
functionality to import GDML data is partially developed (see #275) and will require ROOT 6.12/04. This will be finalized in January, but ROOT 6.12/04 has TEve broken, so at least one more ROOT release is needed, to get everything working.

**Comment by petricm** [comment]
This is just a comment on ROOT 6.12/04. If you apply this [diff](https://github.com/root-project/root/commit/c402d13c6dca83d91d780922ac81d47d8b79d5c9) this should solve the TEve issues (avoids having to create object of type that 'only' inherits from class that overload Hash, but do not overload it themselves). But there is no tag as for now.

**Comment by MarkusFrankATcernch** [comment]
Hi Whit,
this is a very interesting and also necessary direction. 
Actually it is the wet dreams of many subdetector software developers...

We have so far pushed this aside, but if this getting really wanted, I will put it on my job list for this spring/summer, but supposedly after the LHC startup. Until then I think I am busy with LHCb online.
Nevertheless, I will have a chat with Andrei Gheata to see if the basics are supported by TGeo and it only has to be picked up or if there is some extensive basic development necessary.
Since we can read several formats, I do not see a basic problem for DD4hep. The plugins should sort of snuggly collaborate. Still the basic need is a tessellated shape in TGeo.

**Comment by MarkusFrankATcernch** [comment]
VecGeom:
I got some time ago the confirmation that VecGeom will be integrated in TGeo (similar way as done in Geant4, where G4 is a client of VecGeom) once the VecGeom developments are stable.
