### ISSUE TITLE
SensitiveDetector types changed by Geant4SensDetActionSequence

### ISSUE THREAD

**Issue by decibelcooper** [AIDASoft/DD4hep#378]
At line https://github.com/AIDASoft/DD4hep/blob/e744354ef544b066e4e5a663d695429e8521e50a/DDG4/src/Geant4SensDetAction.cpp#L249, `Geant4SensDetActionSequence` changes the type string of the corresponding `SensitiveDetector`.  I find this to be confusing in a multithreaded environment (Using G4MTRunManager) where each thread has to set up its own sensitives.  After the first thread, each thread sees 'Geant4SensDet' as the type for all `SensitiveDetector`s, and so this type string cannot be used to determine the assignment of actions.

It is not hard to create a workaround for this, but I suggest that it may be best for clarity if the sequence does not modify the SD type string.

**Comment by MarkusFrankATcernch** [comment]
I agree. This looks much more like a bug rather than a feature.
I have to see in the code why this was actually done like this and
if there was a real reason for.

**Comment by MarkusFrankATcernch** [comment]
After some digging in the code I think the main reason is that some programmers assign rather arbitrary types. However, for the time being we only have implementations for trackers and calorimeters.

1) When the sequencer is created, the type is reset to "Geant4SensDet". This is actually the name of a generic factory used for all sensitive detectors, which develop a personalization according to the attached sequencer (used in Geant4DetectorSensitivesConstruction::constructSensitives).

2) However, the control is in python and it is expected that the calls "setupTracker" or "setupCalorimeter" are called. These calls then assign explicitly "tracker" or "calorimeter" ie. what ideally was present before. These strings are a bit special, because they are used in the truth handling and anything "creative" invented by users would be counter 

3) In principle the net result is no change. However, since we are in a multi-threaded environment, this could cause a not necessary race condition - which obviously should be avoided.

The whole usage is unfortunately not entirely clear from pure visual inspection of the code.

**Comment by decibelcooper** [comment]
@MarkusFrankATcernch thanks for the feedback!  AFAICT, `setupTracker` and `setupCalorimeter` set the type strings _before_ creating the sequence.  This seems to me to have a net change of the type.

As I understand, the type is changed so that the `Geant4SensDet` plugin is created here: https://github.com/AIDASoft/DD4hep/blob/e744354ef544b066e4e5a663d695429e8521e50a/DDG4/plugins/Geant4DetectorSensitivesConstruction.cpp#L88-L89.  This means that the type cannot be changed back until after the detector construction sequence is actually performed, which sort of excludes it from being done at all in the python setup.

IMO, the solution is for the DD4hep library to not modify `SensitiveDetector::type()`, and also not use this type for specifying the name of the `G4VSensitiveDetector`-inheriting plugin.  Instead, I think that perhaps the `G4VSensitiveDetector` should be specified explicitly by the `Geant4DetectorSensitivesConstruction`.
