### ISSUE TITLE
Trap shape

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#395]
The following shape does not look like it should:
```
 _ns.addSolid(name, Trap(pDz, theta, phi, pDy1, pDx1, pDx2, alp1, pDy2, pDx3, pDx4, alp2));
```
Using G4Trap manual parameters to verify against CMS DD:
![screenshot 2018-05-30 11 28 00](https://user-images.githubusercontent.com/1390682/40711966-c529397e-63fc-11e8-99d8-16f70781b725.png)

Left - CMS DD, right - DD4Hep:
![screenshot 2018-05-30 11 01 06](https://user-images.githubusercontent.com/1390682/40711984-ce98100c-63fc-11e8-873c-340e6d55ec6e.png)

![screenshot 2018-05-30 11 33 18](https://user-images.githubusercontent.com/1390682/40712371-d754c0d6-63fd-11e8-8e7d-f112174f2730.png)
![screenshot 2018-05-30 11 36 48](https://user-images.githubusercontent.com/1390682/40712372-d76f67a6-63fd-11e8-8114-997d2b0bda85.png)
![screenshot 2018-05-30 11 39 00](https://user-images.githubusercontent.com/1390682/40712482-24bf13ee-63fe-11e8-9dc5-73af0cdbb916.png)

**Comment by petricm** [comment]
Do I understand correctly, that you say that left is CMS DD which is equivalent/verified to Geant4 and right is DD4hep?

**Comment by petricm** [comment]
As far as I see the conversion from DD4hep trap to TGeoTrap is ok

https://github.com/AIDASoft/DD4hep/blob/37a4d0743ee2f91baa4b8d2f950037d52b1bf358/DDCore/src/Shapes.cpp#L477-L481

and the conversion to Geant4 seems to be ok also

https://github.com/AIDASoft/DD4hep/blob/05b5bb59cc754642d82c193777dacdcd0fce68c0/DDG4/src/Geant4Converter.cpp#L524-L529

with "the half length in z, the polar angles from the centre of the face at low z to that at high z, H1 the half length in y at low z, LB1 the half length in x at low z and y low edge, LB2 the half length in x at low z and y high edge"

**Comment by ianna** [comment]
@petricm - it looks like you do the double conversion from degrees to radians.

**Comment by petricm** [comment]
Thank you for spotting this, but it's a deeper problem, firstly on the surface you are right
```cpp
TGeoTrap(z, theta, phi, y1, x1, x2, alpha1/units::deg
```
should be
```cpp
TGeoTrap(z, theta/units::deg, phi/units::deg, y1, x1, x2, alpha1/units::deg
```

But this uncovered a more deeper lying problem. We always say TGeo units are DD4hep units, but this is and is not the case, since @gaede introduced a modified TGeo units set

https://github.com/AIDASoft/DD4hep/blob/eedfc8f1cc7b46ff97acb1275cb546d98a7f1673/DDParsers/include/Evaluator/DD4hepUnits.h#L101-L111

but since ROOT version 6.12 instead of using this file we forward from ROOT the **actual** [TGeoUnit](https://root.cern.ch/doc/v612/namespaceTGeoUnit.html). Which means that you get different behavior depending on the ROOT version you use. We are looking into how to resolve this...

**Comment by ianna** [comment]
@MarkusFrankATcernch - Thanks! It's fixed.
<img width="950" alt="screen shot 2018-06-01 at 09 07 07" src="https://user-images.githubusercontent.com/1390682/40826548-3bc26b80-657b-11e8-8e9a-168ba76f784e.png">
