### ISSUE TITLE
Units inconsistency

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#398]
This replaces #395 
There is a inconsistency in the definition of DD4hep units. We always say TGeo units are DD4hep units, but this is and is not the case, since @gaede introduced a modified TGeo units set

https://github.com/AIDASoft/DD4hep/blob/eedfc8f1cc7b46ff97acb1275cb546d98a7f1673/DDParsers/include/Evaluator/DD4hepUnits.h#L101-L111

but since ROOT version 6.12 instead of using this file we forward from ROOT the **actual** [TGeoUnits](https://root.cern.ch/doc/v612/namespaceTGeoUnit.html). Which means that you get different behavior depending on the ROOT version you use. To be discussed on the [next developers meeting](https://indico.cern.ch/event/655518/).

**Comment by gaede** [comment]
Hi Marko,

in our DD4hep units file we actually say that we use units similar to TGeo - with the exception of `radian=1.0`:

```
// System of Units for dd4hep - similar to Geant3 and TGeo/ROOT
//
// Taken from CLHEP with the following basic translations:
//
// Geant4                                   dd4hep
// ----------------------------------------------------------------
// millimeter         mm=1,cm=10            centimeter  mm=0.1,cm=1
// nanosecond         s=1e9                 second      ns=1e-9,s=1
// Mega electron Volt GeV=1e3               GeV         GeV=1
// radian             rad=1                 rad = 1  //NB: different from TGeo
```
As far as I am concerned this is the one and only sensible definition of a unit for the angle, as otherwise you would have 
```
sin( 90. * degree ) = sin( pi /2. * radian ) != 1       !!!!
```
So I think the simple solution to the problem is keep the DD4hepUnits.h  file as is and tell people (if they ask) we use TGeo units except for the angle.

I have to admit that I had forgotten about this, when we discussed forwarding the newly introduced TGeoSystemOfUnits.h.   Could this actually be the reason that including this file causes some tests to fail ?

**Comment by gaede** [comment]
PS: I don't think this is a bug - it would only be a bug if we would forward the TGeo units, which we don't:
https://github.com/AIDASoft/DD4hep/blob/eedfc8f1cc7b46ff97acb1275cb546d98a7f1673/DDParsers/include/Evaluator/DD4hepUnits.h#L32-L40

**Comment by petricm** [comment]
We do

https://github.com/AIDASoft/DD4hep/blob/db205f843790be2fdac183be5b0ae88a734a7189/DDCore/python/dd4hep_base.py#L246-L263

**Comment by gaede** [comment]
Ok, then this is the bug: we are doing something different (and wrong) in python compared to what we do in C++. The python code should then really include the DD4hepUnits.h

**Comment by petricm** [comment]
I thought that the aim of DD4hep was not to do this
![what we have done](https://imgs.xkcd.com/comics/standards.png)

**Comment by petricm** [comment]
We leave the units as they are, but for future reference we refrain from saying that TGeo units are DD4hep units with a caveat, but that DD4hep units are a separate set of units. A section in the manual is to be written...
