### ISSUE TITLE
Installation of CMake macros and config

### ISSUE THREAD

**Issue by jlingema** [AIDASoft/DD4hep#49]
At the moment all macros (DD4hep/cmake/*.cmake, see [here](https://github.com/AIDASoft/DD4hep/blob/master/CMakeLists.txt#L147)) are installed in `${CMAKE_INSTALL_PREFIX}/cmake` except for the DD4hepConfig.cmake, which is installed in `${CMAKE_INSTALL_PREFIX}/.`. Most packages in the LCG stack put the config into `${CMAKE_INSTALL_PREFIX}/cmake` and with the current view creation the macros end up in the view, while the config does not.

**Comment by petricm** [comment]
This can be done without consequences, [since](https://cmake.org/cmake/help/v3.0/command/find_package.html), cmake searches for a configuration file in several directories. Each entry is meant for installation trees following Windows (W), UNIX (U), or Apple (A) conventions:

```
<prefix>/                                               (W)
<prefix>/(cmake|CMake)/                                 (W)
<prefix>/<name>*/                                       (W)
<prefix>/<name>*/(cmake|CMake)/                         (W)
<prefix>/(lib/<arch>|lib|share)/cmake/<name>*/          (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/                (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (U)
```

On systems supporting OS X Frameworks and Application Bundles the following directories are searched for frameworks or bundles containing a configuration file:

```
<prefix>/<name>.framework/Resources/                    (A)
<prefix>/<name>.framework/Resources/CMake/              (A)
<prefix>/<name>.framework/Versions/*/Resources/         (A)
<prefix>/<name>.framework/Versions/*/Resources/CMake/   (A)
<prefix>/<name>.app/Contents/Resources/                 (A)
<prefix>/<name>.app/Contents/Resources/CMake/           (A)
```
However the UNIX default is lib/share (like Geant4) and not cmake/ (like ROOT)

**Comment by jlingema** [comment]
Just to re-iterate and make sure there are no misunderstandings. This is something that does only not work in the LCG-view creation (in case you are not familiar with the views, they are `/usr/local`-like file tree that contains all lcg software). The LCG installation of DD4hep itself works fine (`/afs/cern.ch/sw/lcg/releases/LCG_87/DD4hep/00-17/x86_64-slc6-gcc49-opt/`) but the config is not copied to the view (`/afs/cern.ch/sw/lcg/views/LCG_87/x86_64-slc6-gcc49-opt/`) -- this is something that could also be changed in the view-creation script.

**Comment by petricm** [comment]
Yes, it is understood, that even if we put the everything in the folder `really/not/standard/location/where/nobody/would/ever/look/at` you can modify the view-creation script to account for  `really/not/standard/location/where/nobody/would/ever/look/at`

**Comment by whit2333** [comment]
For the sake of not polluting the install prefix, I would recommend what Joschka  is prehaps hinting at:
install  `DD4hepConfig.cmake` to `$CMAKE_INSTALL_PREFIX/cmake` instead of `$CMAKE_INSTALL_PREFIX` instead. 

Furthermore the generated documentation should probably go into `$CMAKE_INSTALL_PREFIX/share/DD4hep/doc` instead of `$CMAKE_INSTALL_PREFIX/doc` where if another project does the same thing it will easily write over the files since. This is the more standard way of doing things.
