### ISSUE TITLE
A minimal example of  DDCMS usage

### ISSUE THREAD

**Issue by rsehgal** [AIDASoft/DD4hep#512]
To understand clearly, can we have a very simple example of detector constructor along with xml for DDDefintion which will create a two coaxial tubes.

What i understood is that for detector constructor we need need to have Algorithm part in xml file for DDCMS, then what is the use of LogicalPartSection and PosPartSection.

So if we have simple example for DDCMS then it will be very much useful to understand the framework.

May i request developers to provide a minimal DDCMS specific example with bare minimal xml file. Which will also allow the learners to understand the framework.

----
 - OS version: Ubuntu 18
 - Compiler version: e.g GCC 7.2
 - DD4hep version: tag 01-10
 - Goal: as describe above
----

**Comment by MarkusFrankATcernch** [comment]
Hi,

there are several issues here:

1) The CMS xml dialect is NOT supported by DD4hep. We did this exercise only to demonstrate that 
DD4hep can adopt nearly any existing dialect ie. also the one developed by CMS. Though we help the developers in CMS to get across any obstacle this xml dialect is not ours. The fact of its presence is to have the CMS experiment to benefit from past investments.

2) A similar excercise was done for LHCb's DDDB notation. Also strongly discouraged for public use.
The examples only serve as an excercise to show the possibility.

3) In DD4hep we actively support the so called "compact" xml notation on which nearly all our examples are based on. Since you apparently do not have an existing code base I take the freedom to suggest using this notation. Firstly it simple, the collaborating constructs (xml and C++ "detector generators") are easy to understand and the xml syntax is open.

Having said this, I am a bit reluctant to provide such an example unless you are a collaboration member of the CMS experiment. If this is the case, I would suggest you first contact Ianna who is actively working on translating the CMS geometry. Otherwise I strongly discourage you from using the CMS xml notation.

Cheers,

Markus

**Comment by rsehgal** [comment]
Hi,
Thanks a lot Markus for the explanation.

Yes i am collaborator member of CMS. Thanks for pointing Ianna, I will try to contact her.

One small technical question.
Is it possible to get the pointer to logical volume defined in one DetectorConstructor in another DetectorConstructor. So that we can create child logical volume in Child DetectorConstructor
and do the  placement of these Child Volume inside Parent in the parent DetectorConstructor.

Thanks,
Raman

**Comment by rsehgal** [comment]
In other words,
Can different Namespace talk to each other ??

Whenever we create any logical volume or solid, we get it registered with Namespace.
So if different Namespace can talk then it may be possible to get the child logical volume in 
parent DetectorConstructor.


Thanks,
Raman

**Comment by MarkusFrankATcernch** [comment]
The following must be taken with some caution:
This is my knowledge from the initial implementation. 
If Yana changed the implementation, the following may not be entirely correct anymore.

1) Yes. Namespaces can talk to each other provided the references are fully qualified
ie. <namespace>:<object>. At parsing time a static context is established, which holds
maps of the created objects. Until this context is cleared sub-sequent parsers can have access
to this context and hence perform lookups. Maybe not out of the box, but this should be feasible with limited effort.

2) In the CMS model detector constructors are not really used. CMS creates a geometry - up to now a structural hierarchy with "subdetectors" and "DetElements" is not built.
The geometry is created by parsing a sequence of xml-scripts.

Markus
