### ISSUE TITLE
Rules for  include syntax

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/DD4hep#662]
Hello,

What are the rules for the `<include ref="..."/>` syntax?

What has to in the included file?

Here are a few issues I have run into:
1. A file included from within the main `<detectors>` tag. When I placed two detectors in the included file, only the first was constructed. When I put the second `<detector>` in another file both were constructed.
2. The  `<properties>` could not be put in the materials file (although outside of `<materials>` tag. Perhaps the `<includes>` section or the `<gdmlFile>`  precludes using the `<property>` tag?
3. It appears the fields need to be in the main xml file or only one `<field>` per include. Not sure which.
4. Some of the SiD compact files includes which start with `<lcdd>` and some start with `<detectors>`.  For example, `SiD/SiD_Ecal.xml` includes `SiD/SiD_EcalBarrel.xml`. The former, included from the main file, starts with the `<lcdd>` tag and includes the latter which does not.    

Thanks in advance!

**Comment by MarkusFrankATcernch** [comment]
Hi Whit,
1) The rules for the include tag are flurry - they depend on *where* the include is placed.
     The included syntax requires extra coding in the parsing of the structures, hence not everywhere
     code can be replaced by include directives. Since the parsing of included files is atomic with
     respect to the parent also the content must be self contained so that not things parsed in 
     the future get referenced.
2) The root tag of any file defines the way the file is handled. For top level files this is actually the factory to be called.
3) The included content must contain valid xml. In principle one should take the xml code of the included file and paste it instead of the  include directive and things should be still fine. 


Now to your points:
add 1): My point 3) is the reason why for you 1) did not work.
add 2): This I cannot verify like this. It should for sure work if included as top level file if all other required constraints are obeyed. See here also add 3).
add 3) +
add 4) Need to respect the parsing sequence of xml tags:
           - a file having an lcdd tag can only have allowed other tags inside: defines, detectors, materials etc.
            - a file included inside the detectors section may only have one single detector root tag
           etc.

Unfortunately this is not really documented, but I hope the explanation helps a bit to clarify.

**Comment by whit2333** [comment]
Thank you Markus!
