### ISSUE TITLE
DDEve: run CLICSiD example failed

### ISSUE THREAD

**Issue by lihe2013** [AIDASoft/DD4hep#669]
Hello,DDEve and DD4hep developers: 
I recently tried to run the DDeve example (CLICSiD)according to the DDEVE users manual. I initialized the geometry sucessfuly with DDEve.xml and next when I tried to add the event data into the geometry ,it seemed failed. The Error are as follows:  
```
Error in <TStreamerSTL::GetSize>: Could not find the TClass for DD4hep::Simulation::Geant4Particle::Particles.
This is likely to have been a typedef, if possible please declare it in CINT to work around the issue

Error in <TStreamerSTL::GetSize>: Could not find the TClass for DD4hep::Simulation::Geant4Particle::Particles.
This is likely to have been a typedef, if possible please declare it in CINT to work around the issue
```

When I tried to open the CLICSiD_Event.root, there are some warnings i think is related to this issue.Here are the logs on the screen:
```
[lihe@stcf01 eve]$ root -l CLICSiD_Events.root 
root [0] 
Attaching file CLICSiD_Events.root as _file0...
Warning in <TClass::Init>: no dictionary for class DD4hep::Simulation::Geant4Particle is available
Warning in <TClass::Init>: no dictionary for class auto_ptr<DD4hep::Simulation::ParticleExtension> is available
Warning in <TClass::Init>: no dictionary for class DD4hep::Simulation::ParticleExtension is available
Warning in <TClass::Init>: no dictionary for class DD4hep::Simulation::Geant4Tracker::Hit is available
Warning in <TClass::Init>: no dictionary for class DD4hep::Simulation::Geant4HitData is available
Warning in <TClass::Init>: no dictionary for class auto_ptr<DD4hep::Simulation::DataExtension> is available
Warning in <TClass::Init>: no dictionary for class DD4hep::Simulation::DataExtension is available
Warning in <TClass::Init>: no dictionary for class DD4hep::Simulation::Geant4HitData::MonteCarloContrib is available
Warning in <TClass::Init>: no dictionary for class DD4hep::Simulation::Geant4Calorimeter::Hit is available
(TFile *) 0x1cf9b00
root [1] .q
```
So what is the exact reason?How can I do to run the example successfully?

Here is my environment:
 - OS version: SLC6
 - Compiler version: GCC 6.2 ，ROOT6
 - DD4hep version: v1-11

**Comment by andresailer** [comment]
The root file CLICSiD_Event.root comes from a too old version of dd4hep, the namespaces have since been renamed so the dictionaries are not found for the mentioned objects.

If you simulate a few events with the current dd4hep version with the detector compact file `DDDetectors/compact/SiD.xml`  and the input file `DDTest/inputFiles/bbudsc_3evt.stdhep` (or anything else as Input) the display should be working

**Comment by lihe2013** [comment]
I tried and it works，thanks so much！
By the way ，Is there any manuals or lessons or reports on the DDEVE? If yes, Where can I get ? I am a newer using the DDeve and have little experience on it, so actually  I need to learn and undertand more about DDeve.

**Comment by MarkusFrankATcernch** [comment]
I have to add a word here....
DDEve is not "officially" part of DD4hep - though it is part of the repository. The fact of the presence of DDEve is simply because when developing DDG4 I wanted to see where actually the hits of tracks are and if the simulation make any sense at all. For this reason DDEve is very primitive and far from a useful event display.
For this reason there is no documentation coming with it and the idea is to sort of keep it since it seems to not create too much trouble. But the future of the ROOT graphics kit is unclear when we start talking about ROOT 7, hence as a corollary the future of DDEve is uncertain.
Thank you for your understanding.

**Comment by petricm** [comment]
We should update the ROOT file
