### ISSUE TITLE
Export and import from CAD

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#768]
Received via mail from Clement and Mike

>I am coming back to you because I believe that the matter is important: we need to establish an easy and efficient way to exchange data (geometries of objects) between CAD programs and DD4HEP. The exchange needs to go both ways.
 >
>For instance, I would like to import in my CAD world the exact shape of the mask designed in DD4HEP. At the same time, I need to be able to send the geometries of forward objects, like the FF quads, to DD4HEP for background studies.
 >
>My question to you is 1/ is this finally possible with what we have at our disposal today and 2/ if not, should we set up a little task force to see how best to do this?

**Comment by petricm** [comment]
Importing CAD objects to DD4hep works, you have to compile DD4hep and have the Assimp library present, then cmake will detects this and build the extension. From LCG_98 the views are configured in way to have this enabled.

A example how to import from CAD can he seen in `examples/DDCAD`

As for the second question if we can dump/export to CAD, this is presently not possible. It it would be possible and how much work it would, maybe @MarkusFrankATcernch can comment?

**Comment by MarkusFrankATcernch** [comment]
OK. Finally there is some interest in this DD4hep package... :-))  very good.
However, the whole topic is quite complex. To give you a more precise idea about what is possible, what may become possible and where I have no hope we have to split up the topic:

1. Importing CAD to DD4hep
2. Exporting DD4hep to CAD

add 1)
To import CAD to DD4hep became an option for two reasons:
- the rather recent occurrence of tessellated shapes in TGeo
- the discovery of ASSIMP as a generic tool to convert various CAD file formats to tessellated shapes. Due to assimp, we have one single conversion method when importing CAD shapes to DD4hep. In other words DD4hep can benefit from any future improvement of libassimp without additional developments.
CAD shapes can currently be imported into DD4hep, a plugin to import volumes using libassimp exists. There is also an example present. However, to fully exploit the potential I would need a Guinea-pig user willing to do some testing and feeding back suggestions, bugs and possible improvements.

There is one global comment to be added here:
We talk here solely about the conversion of geometry. For example, no CAD tool has a notion of a "sensitive detector"
or a "sensitive volume". This originates from the Geant4 glossary and consequently such entities cannot be imported. After an import the corresponding volumes would require to be patched "by hand" ie. by applying some plugin.

add 2)
To export DD4hep to CAD is not at all simple.
Firstly, there is no equivalent to libassimp present. Hence, any direct export to a given CAD file format is not possible. The
only possibility left is indirect conversion with intermediate formats. The only known way is quite tedious:
- `DD4hep -> GDML (ROOT) -> STEP`
- `DD4hep -> Geant4 -> GDML (G4) -> STEP`
The last step of this conversion sequence was never tested. It also requires that your CAD tool understands such STEP files.

In general:
- I do not know which formats in general are understood by  CAD tools. Hence, I do not know up to which degree the export of DD4hep geometries to CAD is actually an option.
- Any of these conversion cycles goes along with a certain  loss of information. Besides the already mentioned information about sensitive elements which is lost when exporting from DD4hep to CAD, also any structural information ie. the tree of DetElements is lost and of course visual attributes. It is not really obvious how to restore this information in a generic manner.
- For the reason above I do not consider the waterfall approach
  `CAD -> DD4hep -> CAD -> DD4hep -> .... `
  as unrealistic on the big scale. To investigate such an approach for one or two volumes might be possible. One has to keep in mind that for re-introducing such a shape from CAD into DD4hep will require customization.
- I personally see the advantage of the DD4hep to CAD interface to easily import shapes/volumes fabricated in a workshop, which are designed by engineers using CAD tool. Such volumes which typically have a quite complex structure depending on the machining can then be imported relatively easily as a tessellated shapes. Such a facility can help to ease the description of the detector significantly.

**Comment by petricm** [comment]
It is written in assimp that "Due to its export interface, Assimp serves as general-purpose 3D model converter" and there is an `Exporter` [class](http://assimp.sourceforge.net/lib_html/class_assimp_1_1_exporter.html) but I don't know if it is usable?

**Comment by MarkusFrankATcernch** [comment]
I believe this is unfortunately only an interface to implement exporters. I cannot imagine that all input formats are also supported for output. Probably only one custom output format is provided.

**Comment by DraTeots** [comment]
> However, to fully exploit the potential I would need a Guinea-pig user willing to do some testing and feeding back suggestions, bugs and possible improvements.

Dear Markus, I'm considering of using DD4HEP for EIC (now we have raw Geant4 geometry) and I probably will be such a Guinea-pig as we need beemline elements there

**Comment by MarkusFrankATcernch** [comment]
@DraTeots Very nice! 
First thing however is to check if your CAD format is understood by ASSIMP
( https://github.com/assimp/assimp , http://assimp.org ) . 
In dd4hep we do not develop converters ourselves. Hence, we sort of should know 
that assimp supports before spending a lot of work.
