### ISSUE TITLE
DD4hep ignores tiny rotation for placed volume

### ISSUE THREAD

**Issue by cvuosalo** [AIDASoft/DD4hep#870]
CMS uses very small rotations for placing some volumes. We have found that when calling `dd4hep::Volume::placeVolume(const Volume& volume, int copy_no, const Transform3D &transform)` with a very small rotation, the rotation is ignored during placement. It can be seen that the DDh4ep code has an explicit check for ignoring small rotations. On lines 635-641 of `Volume.cpp` we can see the check:
```
  const Double_t* r = transform->GetRotationMatrix();
   if ( r )   {
     Double_t test_rot = r[0] + r[4] + r[8] - 3.0;
     if ( TMath::Abs(test_rot) < 1E-12)
       transform->ResetBit(TGeoMatrix::kGeoRotation);
     else
       transform->SetBit(TGeoMatrix::kGeoRotation);
 ```
One of the small rotations used by CMS is the following:
```
0.9999999999997518651539963  -4.963671546650112873122791e-13  7.045385025004133009251628e-07
0  0.9999999999997518651539963  7.045280746237101409252786e-07
-7.045385025005881073496524e-07  -7.04528074623535334500789e-07  0.9999999999995037303079926
```
The values along the diagonal differ from 1 by the following amounts:
```
Diagonal - 1 = -2.481348460037224867846817e-13 -2.481348460037224867846817e-13
 -4.962696920074449735693634e-13
```
This rotation does have an effect, though tiny, so we need to be able to apply it to placed volumes. Maybe the test in `Volume.cpp` could be changed to check for < 1.E-13 to allow this rotation to be applied.

**Comment by MarkusFrankATcernch** [comment]
There is nothing to comment here really. At a time it was thought that this limit is small enough.
If this turns out not to be the case we can easily lower the limit. The only important thing is to not run into problems with
numerical limits which should not be the case for something around 1e-14 or so.
1e-12 however is a value I have seen several times in ROOT before, so there may be additional occurrences of such
incidents.
I will change it for the next commit I do.

**Comment by MarkusFrankATcernch** [comment]
@cvuosalo  Please see: https://github.com/AIDASoft/DD4hep/pull/871

**Comment by cvuosalo** [comment]
@MarkusFrankATcernch Thanks so much for so quickly resolving this issue.
