### ISSUE TITLE
question: how to implement gaps in segmentations

### ISSUE THREAD

**Issue by c-dilks** [AIDASoft/DD4hep#958]
I'm trying to model a photosensor with an 8x8 grid of pixels, and am wondering how to handle the small 0.2 mm gaps between the pixels (see XML snippet below). Is there some way to add gaps to a segmentation, or should the gaps be implemented in the geometry itself (in which case I suppose we wouldn't need the segmentation)?

```xml
<constant name="num_px"             value="8"/>      <!-- number of pixels along one side of the sensor -->
<constant name="sensor_pixel_pitch" value="3.2*mm"/> <!-- center-to-center distance between SiPMs in a 8x8 panel -->
<constant name="sensor_pixel_size"  value="3.0*mm"/> <!-- a single SiPM pixel size -->

</documentation>
<readouts>
  <readout name="hits">
    <segmentation
      type="CartesianGridXY"
      grid_size_x="sensor_pixel_pitch*num_px/(num_px-1)"
      grid_size_y="sensor_pixel_pitch*num_px/(num_px-1)"
      offset_x="-sensor_pixel_pitch*num_px/2.0"
      offset_y="-sensor_pixel_pitch*num_px/2.0"
      />
    <id>system:8,sector:3,module:12,x:23:16,y:16</id>
  </readout>
</readouts>
```

**Comment by andresailer** [comment]
I don't think we have a segmentation that can support this at the moment.

To do this without splitting the sensitive volume into individual pieces one would need to create a new sensitive detector that ignores the energy deposited in the respective area (volume), together with a new segmentation that can account for the gaps.

Or you reduce the segmentation grid size and get rid of hits in the dead area post simulation.

**Comment by MarkusFrankATcernch** [comment]
@c-dilks 
1) Modelling the segmentation at the level of the geometry is not a good idea in the present of many segmentation cells.
The memory would very likely start to explode due to a huge number of physical volume placements.

2) One way to model such a behavior would be to implement it at the level of the reconstruction/digitization and sort of ignore hits falling into the gaps. This would have the advantage that
-- a re-segmentation to a a larger segmentation grid would be possible during the reconstruction
-- charge sharing between strips/pixels separated by small gaps could be implemented as well.

At least to me 2) looks much more attractive rather than removing deposits at the level of the simulation. However, I am not really an expert in this area.

**Comment by c-dilks** [comment]
Thanks for the advice. It seems like the best way forward for us is to implement gaps in the reconstruction stage, especially in light of point 2) from @MarkusFrankATcernch
