### ISSUE TITLE
still problems with cerenkov

### ISSUE THREAD

**Issue by saraheno** [AIDASoft/DD4hep#966]
Hi,
I spoke too soon.  by setting the verbose level in the python function in the steering that turns on the cherenkov radiation, it is clear that geant4 is making cherenkov radiation.  However, it does not seem to be getting to my SDAction code.  

is https://github.com/AIDASoft/DD4hep/blob/eefa03bdeb900033012257a4849a5834a3586caa/DDG4/src/Geant4ParticleHandler.cpp#L51

the line where DDG4 calls the user SDAction code?

(my code is at https://github.com/saraheno/SingleDualCrystal  and the SDAction is in the src subdirectory

Best
Sarah Eno

**Comment by saraheno** [comment]
actually, I think they are getting rejected here: https://github.com/AIDASoft/DD4hep/blob/master/DDG4/src/Geant4ParticleHandler.cpp#L186  
?  could that be why they are not getting to my SDAction?

**Comment by andresailer** [comment]
The particle handler is only about which particles to save, not about what happens in sensitive detectors.

**Comment by saraheno** [comment]
okay, where would I find the call to the SDAction?  I want to try to figure out why the cerenkov photons are not entering my SDAction.  Other particles are...

**Comment by saraheno** [comment]
Is it this line  https://github.com/AIDASoft/DD4hep/blob/eefa03bdeb900033012257a4849a5834a3586caa/DDG4/src/Geant4SensDetAction.cpp#L415

**Comment by saraheno** [comment]
I think they are being rejected at https://github.com/AIDASoft/DD4hep/blob/eefa03bdeb900033012257a4849a5834a3586caa/DDG4/src/Geant4SensDetAction.cpp#L154


are all these filters set in the steering?  are there any set any where else?

**Comment by MarkusFrankATcernch** [comment]
- Do you have any particle filters attached ?
- If there are no particle filters, Geant4Sensitive::accept returns always true and should not throw away the hits and `Geant4SensitiveAction<DualCrystalCalorimeterSD>::process` should be called.
- In line 77 of https://github.com/saraheno/SingleDualCrystal/blob/main/src/DRCrystal_geo.cpp you declare the crystal as a "calorimeter". 
- In python did you remap `calorimeter` to your sensitive detector or alternatively explicitly attach the sensitive detector directly ? otherwise you will never get a call in `Geant4SensitiveAction<DualCrystalCalorimeterSD>::process`. This mapping is crucial. Otherwise you get calls to `Geant4CalorimeterAction` which is the default for `calorimeter`. You have to set in python:
```
  geant4 = DDG4.Geant4(kernel)
  geant4.sensitive_type['calorimeter'] = "DualCrystalCalorimeterSDAction"
```
This normally should do the job and route all deposits from Geant4 to your SD action.

**Comment by saraheno** [comment]
I put couts in the accept, and it is definitely returning false for optical photons.


If there are any filters, are they in the steering?  My steering is  https://github.com/saraheno/SingleDualCrystal/blob/main/compact/SCEPCALsteering.py

**Comment by MarkusFrankATcernch** [comment]
I see here in line 142 `SIM.filter.calo = "edep0"` ... this perhaps may be your killer if the threshold is very small.

**Comment by saraheno** [comment]
I tried commenting that out and it did not fix it.  I did try hardwiring accept to true and then it worked.  I guess I don't know how to see which filters are being used and the individual true/false for each one?

**Comment by andresailer** [comment]
The Cerenkov photons do not deposit energy, so `energyDeposit > 0` is already too much.
You can disable all filters with
```
SIM.filter.calo = ""
```
Commenting out doesn't work, because `edep0` is the default and will be used if nothing is set in the steering file or command line.

**Comment by andresailer** [comment]
I added print out to ddsim to make it more obvious if a filter is applied to a sensitive detector or none are applied. But this only happens at startup.
